services:
    app:
        container_name: jc-app
        image: smeag0l/jet-centre:prod
        env_file:
            - .env.production
        environment:
            - NODE_ENV=production

        restart: always
        ports:
            - '[::]:80:3000'
        networks:
            - db-network
            - internet
        depends_on:
            - postgres

    postgres:
        image: postgres:15
        container_name: jc-postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: maindb
        volumes:
            - postgres:/var/lib/postgresql/data
        networks:
            - db-network
    watchtower:
        container_name: watchtower
        image: containrrr/watchtower
        restart: always
        environment:
            - WATCHTOWER_CLEANUP=true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ~/.docker/config.json:/config.json:ro
        command: --interval 30 jc-app

networks:
    db-network:
        external: false
    internet:
        enable_ipv6: true

volumes:
    postgres:
    bun-cache:
    app-data:
