services:
    nextapp:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - postgres
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mydatabase
        networks:
            - app-network

    postgres:
        image: postgres:15
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: mydatabase
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    pgdata:
