services:
    postgres:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: maindb
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network

    cache:
        image: redis:latest
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - cache:/data
        networks:
            - app-network

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app-prod
        ports:
            - '4000:5005'
        environment:
            NODE_ENV: production
        #     DATABASE_URL: postgres://postgres:postgres@postgres:5432/mydatabase
        #     REDIS_URL: redis://cache:6379/0
        env_file:
            - .env.prod
        depends_on:
            - postgres
            - cache
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    postgres_data:
    cache:
