services:
    postgres:
        image: postgres:15
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: maindb
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network

    cache:
        image: redis:latest
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - cache:/data

    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: app-dev
        volumes:
            - .:/app
            # - /app/node_modules # Prevent overwriting node_modules
        ports:
            # For the app
            - '5005:5005'
            # For prisma studio
            - '5555:5555'
        environment:
            - DB_URL=postgres://postgres:postgres@postgres:5432/maindb?schema=public
            - REDIS_URL=redis://cache:6379/0
        env_file:
            - .env.local
        depends_on:
            - postgres
            - cache
        networks:
            - app-network
        command: npm run dev

networks:
    app-network:
        driver: bridge

volumes:
    postgres_data:
    cache:
