name: Enforce Conventional Commits

on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - '*'

jobs:
    pr-lint:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest

        steps:
            - uses: amannn/action-semantic-pull-request@v5
              with:
                  types: |
                      feat
                      fix
                      chore
                      docs
                      style
                      refactor
                      perf
                      test
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    push-lint:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: wagoid/commitlint-github-action@v5

    build:
        name: Conventional Commits
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: webiny/action-conventional-commits@v1.3.0
              with:
                  allowed-commit-types: 'feat,fix,chore,docs,style,refactor,perf,test'
