name: Deploy doc to GItHub pages

on:
    push:
        branches:
            - 'main'
    pull_request:
        branches:
            - 'main'
permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun i

            - name: Generate prisma doc
              run: bun x prisma generate

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs/schema
