name: Knip Analysis

on:
    push:
        branches:
            - '*'

jobs:
    knip:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun i

            - name: Run Knip
              run: bun x knip
