name: pipeline
on:
    push:
        branches:
            - prod
            - preprod

jobs:
    deploy:
        name: build && push image to docker hub
        runs-on: ubuntu-latest
        if: github.repository == 'Telecom-Etude/jet-centre'
        steps:
            - uses: actions/checkout@v3

            - name: setup docker buildx
              uses: docker/setup-buildx-action@v2

            - name: docker login
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: set docker tag
              id: vars
              run: |
                  if [[ "${GITHUB_REF_NAME}" == "prod" ]]; then
                    echo "TAG=prod" >> $GITHUB_ENV
                  elif [[ "${GITHUB_REF_NAME}" == "preprod" ]]; then
                    echo "TAG=preprod" >> $GITHUB_ENV
                  fi

            - name: build and push api
              id: build-push-api
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: Dockerfile
                  target: runner
                  push: true
                  tags: smeag0l/jet-centre:${{ env.TAG }}
